In [2]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
multi_array = np.array([[1,2,3],[3,4,5]])
multi_array[1]

array([3, 4, 5])

In [4]:
import numpy as np
autoarray = np.zeros(10)
autoarray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
autoarray.dtype

dtype('float64')

In [6]:
autoarray = autoarray.astype(np.int64)
autoarray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])